import { MigrationGenerating } from '@typing/generating.interface';
import { MongoClientOptions } from 'mongodb';

/**
 * @private
 */
export interface MongoDocument {
    _id: string;
    name: string;
    timestamp: Date;
}

/**
 * Migration configuration
 */
export interface MigrationMongo {
    /**
     * Mongo connection url or object with config
     * @example "mongo://mongo:mongo@localhost:27017/database"
     */
    uri: string;

    /**
     * Optional object with options
     */
    options?: MongoClientOptions;

    /**
     * Collection name with history of executed migration
     * @default "migrations"
     */
    collection?: string;

    /**
     * Configuration for autogenerated migrations
     */
    generating?: MigrationGenerating;
}
