networks:
  quazex_migrator_network:

volumes:
  quazex_migrator_volume:

services:
  postgresql:
    image: postgres:16.1
    container_name: quazex_migrator_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: quazex
      POSTGRES_PASSWORD: quazex
      POSTGRES_DB: quazex
    volumes:
      - quazex_migrator_volume:/var/lib/postgresql/data
      - ./.docker/postgres.init.sql:/docker-entrypoint-initdb.d/postgres.init.sql
    networks:
      - quazex_migrator_network
    ports:
      - 35432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quazex -t 10"]
      interval: 2s
      timeout: 10s
      retries: 2
