import { type ClientConfig } from 'pg';
import { MigrationGenerating } from '../typing/generating.interface';

/**
 * @private
 */
export interface PostgresDocument {
    id: string;
    name: string;
    timestamp: Date;
}

/**
 * Migration configuration
 */
export interface MigrationPostgresConfig {
    /**
     * Postgres connection url or object with config
     * @example "postgresql://postgres:postgres@localhost:5432/database"
     */
    connection: string | ClientConfig;

    /**
     * Table name with history of executed migration
     * @default "migrations"
     */
    table?: string;

    /**
     * Configuration for autogenerated migrations
     */
    generating?: MigrationGenerating;
}
