name: Release

on:
  push:
    branches: [ main ]

env:
  HUSKY: 0
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      packages: write
      contents: write
      issues: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Docker
        uses: ScribeMD/docker-cache@0.3.6
        with:
          key: docker-${{ runner.os }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Deps
        run: npm ci

      - name: Build module
        run: npm run build:compile

      - name: Release
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
